name: Release package
on:
  release:
    types: [published]
permissions:
  id-token: write
  contents: read
jobs:
  release:
    name: Release package
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x

    - name: Create package
      run: dotnet pack -c Release -p:Version=${{ github.event.release.tag_name }}

    - name: Archive package
      uses: actions/upload-artifact@v7
      with:
        archive: false
        path: ./artifacts/package/release/QuestPDF.Markdown.${{ github.event.release.tag_name }}.nupkg

    - name: NuGet login (OIDC to temp API key)
      id: login
      uses: NuGet/login@v1
      with:
        user: ${{ secrets.NUGET_USER }}

    - name: Publish package (NuGet)
      run: dotnet nuget push ./artifacts/package/release/*.nupkg --api-key ${{ steps.login.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
